name: dsci_522_project_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12.12
  - pandas=2.2
  - jupyterlab=4.0
  - numpy=1.26
  - scikit-learn=1.7.2
  - matplotlib=3.10.8
  - pandera-pandas=0.27.0
  - scipy=1.16.3
  - shap=0.48.0  # Breaking changing in model output format https://github.com/shap/shap/issues/3581
  - tabulate=0.9.0
  - pip=25.3
  - altair=5.5
  - vegafusion-python-embed=1.6.9 #Must be same version as vegafusion below to prevent crashing
  - vegafusion=1.6.9 # Must be same version as vegafusion above to prevent crashing
  - vl-convert-python=1.8.0 # version to let the solver find a compatible version for osx-64 
  - conda-lock=3.0.4
  - quarto=1.8.26
  - pip:
      - ucimlrepo==0.0.7 #Remove version pinning to ensure conda-lock operation can run
      - altair_ally==0.1.1 # New default plotting behavior
