name: DSCI_522_project_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pandas=2.2
  - jupyterlab=4.0
  - numpy=1.26
  - scikit-learn=1.4
  - matplotlib
  - shap
  - tabulate=0.9.0
  - pip
  - altair=5.5
  - vegafusion-python-embed=1.6.9 #Must be same version as vegafusion below to prevent crashing
  - vegafusion=1.6.9 # Must be same version as vegafusion above to prevent crashing
  - vl-convert-python=1.7.0
  - pip:
      - ucimlrepo
