name: DSCI_522_project_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pandas=2.2
  - jupyterlab=4.0
  - numpy=1.26
  - scikit-learn=1.4
  - matplotlib
  - shap
  - tabulate=0.9.0
  - pip
  - altair=5.5
  - pip:
      - ucimlrepo
