name: DSCI_522_project_env
channels:
  - conda-forge
  - defaults
dependencies:
  - conda==23.11.0
  - python=3.9
  - pandas==2.2.1
  - jupyterlab==4.0.10
  - numpy==1.26.4
  - scikit-learn==1.4.0
  - matplotlib==3.8.2
  - shap==0.39.0
  - tabulate=0.9.0
  - pip==24.0
  - altair=5.3.0
  - vegafusion-python-embed=1.6.9 #Must be same version as vegafusion below to prevent crashing
  - vegafusion=1.6.9 # Must be same version as vegafusion above to prevent crashing
  - vl-convert-python=1.7.0
  - pip:
      - ucimlrepo