name: DSCI_522_project_env
channels:
  - conda-forge
dependencies:
  - python>=3.11,<3.13
  - pandas=2.2
  - jupyterlab=4.0
  - numpy=1.26
  - scikit-learn
  - matplotlib
  - pandera-pandas
  - shap>=0.45  # Breaking changing in model output format https://github.com/shap/shap/issues/3581
  - tabulate=0.9.0
  - pip
  - altair=5.5
  - vegafusion-python-embed=1.6.9 #Must be same version as vegafusion below to prevent crashing
  - vegafusion=1.6.9 # Must be same version as vegafusion above to prevent crashing
  - vl-convert-python>=1.7.0 # version to let the solver find a compatible version for osx-64 
  - pip:
      - ucimlrepo
      - altair_ally>=0.1.1 # New default plotting behavior
